TheRestartProject/restarters.net

- .gitignore
- app/Http/Controllers/PartyController.php
- tests/Feature/Events/CreateEventTest.php
I tested this by:
- Creating an event in the past
- Removing myself from the list of attendees
- Trying to re-add myself; I don't show in the list
The code looks as though it was intentionally excluding the logged-in user, but I don't think that's correct.
> DOT-812 Allow host to be added to event later

- public/css/app.css
- resources/assets/sass/_alert.scss
- resources/views/layouts/header_plain.blade.php
We've been talking as though this was device/browser specific, and that's why we needed Browserstack.  But I think it's a general problem with the alert colours, which reproduces on Chrome.
_alert.scss defines a font colour of #FFF and different background colours for the alert variants. The background colour for alert-success would be unreadable wherever it was used.  Given that alert-primary has a background colour of $brand, I've set that for alert-success too.  That gives this:
That's a different change than James suggested, but I think it's probably better to stick to the brand colours.
> Forgot password colour

- resources/assets/js/app.js
- resources/assets/js/components/EventDatePicker.vue
- resources/assets/js/components/EventTimeRangePicker.vue
- resources/views/events/create.blade.php
- resources/views/events/edit.blade.php
@edwh would be great to get your feedback on this code!
For DOT-1346, the issue was that we're using inputs with type=time, and that Safari on desktop doesn't support this.
I've used bootstrap-vue's b-form-timepicker component to replace the time range selection.  I've used a hidden input who's value is bound to the value of the timepicker in order to pass the value to the server on form submit.
I've used the agent checker library we have so that we only use this component on desktop Safari, and stick with the browser's own component elsewhere (chiefly because I think it's better to use the browser's native components when they do exist).  Side note: it would be better to do a check on support for input type=time rather than check for a specific browser, but I don't know how to do that. …
> Dot 1346 safari timepicker

- resources/views/group/view.blade.php
We noticed that the pencil icon for editing volunteers was missing. This fixes that.
> Permission check lost in recent restructure

- app/Http/Controllers/GroupController.php
- resources/assets/js/components/CollapsibleSection.vue
- resources/assets/js/components/GroupEvents.vue
- resources/assets/js/components/GroupEventsPage.vue
- resources/views/events/index.blade.php
Add button in collapsible section should be on the right hand side
Remove a couple of double full-stops.
No past events showing on mobile group events page.
Edit flags not being passed down in group events page.
> Various bugs on events page

- app/Http/Controllers/GroupController.php
The front end code already displays the pencil appropriately.  This change modifies the permission check to allow a network coordinator to make someone a host.
It doesn't seem right to me that network coordinator is a user-level field.  You could surely be a coordinator of one network and not have that role on others.  So I may be missing something here - please review the logic.
> Allow network administrator to make someone a host

- app/Http/Controllers/CalendarEventsController.php
- resources/views/group/view.blade.php
This was a bug introduced by me in DOT-1315.  I've fixed the case causing an error, and added a similar protection in the other place it might apply (it doesn't at the moment, but is safer and clearer code).
> DOT-1367 User's calendar link returns an error

- app/Http/Controllers/DeviceController.php
Missing bit of code in DeviceController::search().
There's duplication between search() and index(), but search() will be removed once DOT-1287 is released.
> DOT-1158 Fixometer showing undefined weight for most recent event after search

- app/Http/Controllers/PartyController.php
- resources/assets/js/components/MicrotaskingVolunteering.vue
- resources/lang/en/events.php
- resources/views/events/create.blade.php
I can't reproduce the original problem, but the code doesn't look like it handles missing locations well.
I've added some validation on the server to reject the create gracefully if no location is supplied and the event is not online.
The user experience is poor for errors on this form - we have basic HTML validation using "required", which means we see the default browser error message when we try to submit something which is missing.  But we don't have any more complex validation, which makes it hard to validation combinations of fields like this, except on the server.  Server-side validation means we lose the form data we submitted.  There are also other error cases (e.g. create an event with an end time after the start time).  
We should rewrite the event creation page into Vue and …
> Prevent error if create event with no location

- resources/wiki/css/components/_search-button.scss
As per the conversation in there, we need to style the wiki search magnifying glass differently.  That's handled in restarters CSS.
> DOT-1247 Style wiki search button

- resources/global/css/components/_buttons.scss
Disabled primary buttons are white text on a white background.
I switched to grey - not sure if we have a convention for disabled?
It took many times longer to track down which of the multitude of CSS fragments was controlling this than to fix it.
> DOT-1359 RSVP invisible

- resources/wiki/css/components/_alerts.scss
Notifications for saved wiki edits aren't appearing above the navbar.  
The way these get added is a bit odd - looks like some CSS rules are dynamically added in.  Took a bit of experimentation to get the right z-index on the right class.
> DOT 1374 MW skin

- resources/assets/js/components/DeviceModel.vue
- resources/assets/js/components/EventDeviceSummary.vue
Errors introduced in tech debt change, where we don't have all the props we need.
> DOT-1386 Can't edit old devices

- resources/assets/js/app.js
- resources/views/group/stats.blade.php
- resources/views/layouts/header.blade.php
- resources/views/layouts/header_nocookie.blade.php
- resources/views/layouts/header_plain.blade.php
- resources/views/party/stats.blade.php
- Create a new 'nocookie' layout, which doesn't include the Google stuff.
- Remove the cookie notice which is then not needed
- Use this from the stats template.
- Stop the global JS barfing.
Tested in Brave to ensure it looks clean.
> DOT-1390 Remove cookies for stats

- resources/assets/js/app.js
- resources/assets/js/components/DashboardYourGroups.vue
We currently do translations in Vue components by having computed properties which call this.$lang.get().  This works but leads to a lot of dull code.
This PR introduces a `__()` method which is in a global mixin and therefore available everywhere.  This is named to match the Laravel translation call, which means it's one fewer thing to remember.  We can then pass in the key directly in a template, e.g. 
```
<p>
{{ __('dashboard.catch_up') }}
</p>
```
I've used it in one example, but if you like this approach then I'll go through and apply it throughout - bit dull to do but removes a bunch of code that doesn't deserve to live.
In Vue 2, filters might be a natural way to do this, and I like them, but they're being retired in Vue 3.  
This has the additional minor advantage of making it …
> Introduce a better translation mechanism

- resources/assets/js/components/FixometerPage.vue
The smallest of fixes - one character typo.
> DOT-1415 Group name lost from Fixometer URL

- resources/assets/js/components/GroupEvents.vue
- resources/lang/en/events.php
This looks like merge issues though I've not dug into the history.  
* On mobile the Add Event is inside the dropdown menu and therefore doesn't need a label and translation.
* On desktop it should use the correct label, and the classes are not needed as the CollapsibleSection has them.
> DOT-1422 Add button mislabelled on group page

- app/Helpers/Fixometer.php
It's no longer used anywhere, probably as a consequence of earlier restructuring of the Discourse stuff, so it can just be removed.
> DOT-1416 Remove deprecated Discourse call

- resources/wiki/css/app.scss
Force a width on the search field to make it appear.
Based on DOT-1427 so will show that as a diff until merged.
> DOT-1426 search bar

- resources/wiki/css/app.scss
Make this look a little better.
* Hide the icon, which adds little and chews up space.  
* Shrink the font slightly.
* Force a width.
> DOT-1427 translation skin

- database/migrations/2021_05_05_151211_audit_issue.php
The migration is a bit unusual because of bugs.
https://stackoverflow.com/questions/37724150/laravel-migrations-change-a-column-type-from-varchar-to-longtext
> DOT-1439_Migrate audit columns to longtext

- app/Device.php
- database/migrations/2021_06_09_164834_no_null_problems.php
- tests/Feature/Devices/NullProblemTest.php
Add a migration to sort out the existing values, and a mutator to ensure no new null values sneak in.
> DAT-529 Use empty strings rather than nulls for empty problems.

- phpunit.xml
- tests/Feature/Admin/Users/ViewUsersTest.php
- tests/Feature/Groups/GroupEditTest.php
- tests/TestCase.php
- tests/Unit/Events/EventPermissionsTests.php
We're now down at a handful of existing tests that don't work, which are excluded in phpuninit.xml.
* Some are ones which integrate with other components (wiki, Wordpress, Zapier).  These probably aren't worth getting running in CircleCI any time soon.
* Some are ones which relate to quests.  Can you think about whether these will disappear or should be made to work?
* One (ExampleTest) uses RefreshDatabase.  Perhaps the stuff I added in TestCase should use that too?  This one could probably be made to work but doesn't feel too important.
So we might be able to move on to adding new tests.  See what you think.
> More tests

- database/migrations/2021_04_06_113426_printcat_ora_setup.php
- database/migrations/2021_05_11_130314_create_microtask_surveys.php
- resources/lang/en/event-audits.php
- resources/views/partials/log-accordion.blade.php
The scenario here is:
- Create an event in the past
- Add a device
- Edit the event
The audit logs contain the new `devices_updated_at `information which is an array, e.g. this:
`{"devices_updated_at":{"date":"2021-06-23 13:37:18.545386","timezone_type":3,"timezone":"Europe\/London"}}`
The method we use to render audit logs fails if a value is an array.
I'm not sure whether or not we ought to be stopping the data getting into the audit log in array form?  But such data now exists in the live DB.  We can make it render acceptably by spotting it and encoding it.
> DOT-1480 500 error when editing an event with added devices

- app/Http/Controllers/PartyController.php
- resources/js/components/GroupEventScrollTable.vue
- resources/js/components/GroupEventsScrollTableActions.vue
- resources/views/events/view.blade.php
- tests/Feature/Events/InviteEventTest.php
Add an invitation property to the even when we've been invited, and use that as the link for the RSVP button.  I don't think we need to change the text of that button in this case, and there's not much room.
Also fix the format of the button on the individual event page when you've been invited, as it doesn't really match the design.
> DOT-1510 RSVP button doesn't work when invited

- app/Party.php
- resources/js/components/EventActions.vue
- resources/js/components/EventHeading.vue
- resources/js/components/EventPage.vue
- resources/js/components/GroupEventsScrollTableNumber.vue
- resources/views/events/view.blade.php
- tests/Feature/Events/DeleteEventTests.php
This adds a canDelete method for events, exposes it to the client so that we can render the relevant option in the menu, and tests the server behaviour.
> DOT-1474 delete events

- resources/js/components/DashboardYourGroups.vue
Add a sort on the client-side to ensure the order is correct - the store isn't guaranteed to return them in that order.
> DOT-1529 dashboard event order

- app/Helpers/Fixometer.php
- app/Helpers/Geocoder.php
- resources/views/events/view.blade.php
- tests/Feature/Events/DeleteEventTest.php
- tests/Feature/Events/OnlineEventsTest.php
- tests/Feature/Users/EditProfileTests.php
- tests/Feature/Users/Registration/AccountCreationTest.php
Rework delete permissions for an event:
- Add a method to query it.  The permissions are different from Edit.  As we know, the permissions could do with being centralised.
- Query that.
- Change/add tests in this area.
> RES-1563 Allow network coordinators to delete events.

- app/Http/Controllers/PartyController.php
- tests/Feature/Events/InviteEventTest.php
The logic for which volunteers are invitable is bugged:
- It included people invited to the group but who have not accepted.  They shouldn't be invitable to an event.
- It included people invited to the event already.  We shouldn't be able to pester people by inviting them twice.
> RES-1587 too many volunteers

- resources/js/components/RichTextEditor.vue
Sentry error caused by missing "this".  It may be benign, but is easy to fix.
> RES-1596 mounted sentry error

- resources/js/components/GroupEvents.vue
- resources/js/components/GroupEventsPage.vue
- resources/js/components/GroupEventsTab.vue
- resources/lang/en/events.php
- resources/views/events/index.blade.php
Add a better prompt.
This is another example where we pass props around because we don't have an "auth" on the client side.  Will add to retro.
> RES-1603 When no location set, events page should prompt to set one

- phpunit.xml
- resources/js/components/EventTimeRangePicker.vue
The current code uses a watch to spot when times have changed.  Suppose you have an event start of '17:00' and an event end of '18:00' which you want to change.  If you type in the field, e.g. '19', what happens is that on the '1' the hour changes to '01'.  Then we spot that '01' is before '17', and is therefore invalid, so we reset it.
This PR waits until you move away from the input, and fires the $emit to change the value then.  This behaves better.
> RES-1595 Change how start/end time changes are handled.

- .circleci/config.yml
- .env.example
- app/Console/Commands/LanguageSync.php
- app/Console/Commands/MigrateWikiPasswords.php
- app/Events/PasswordChanged.php
- app/Http/Controllers/UserController.php
- app/Listeners/ChangeWikiPassword.php
- app/Listeners/LogInToWiki.php
- app/Providers/MediawikiServiceProvider.php
- resources/lang/en/passwords.php
- tests/Feature/Users/PasswordResetTest.php
- tests/Feature/Users/RecoverTest.php
- tests/TestCase.php
Lots of good stuff.
- Add Mediawiki image to the CircleCI configuration and enable wiki integration.  This means our tests now run with a real wiki.
- Change Mediawiki passwords to use the hashed Laravel password.
- Add a test of password recovery/reset.  This needs the code to be a bit more standard Laravel (avoid $_POST etc).
- Add a command to generate the Mediawiki commands to run from maintenance/ to migrate the passwords.
- Make the test users more unique, because we don't clean out the wiki users between tests.
> RES-1521 password reset

- app/Console/Commands/MigrateWikiPasswords.php
- app/Listeners/CreateWordpressPostForEvent.php
- app/Listeners/EditWordpressPostForEvent.php
- tests/Feature/Events/WordpressEventPushTest.php
Ensure that the event start/end pushed to Wordpress doesn't contain seconds.
> RES-1607 Wordpress event time

- app/Group.php
- app/Listeners/CreateWordpressPostForGroup.php
- app/Services/DiscourseService.php
- database/migrations/2022_01_04_123128_group_discourse_logo.php
Enhance Discourse sync to apply any group logo to the Discourse group as a flair URL.  
I’ve not added an automated test, as:
- It’s so dependent on the Discourse API that mocking would make it a bit pointless.
- Testing it properly in the Docker Discourse environment would be quite a lot of work.
- I’ve added logs in the error cases so that they will show up in Sentry.
> RES-1608 discourse group logo

- app/Party.php
We were passing an EventsUsers instance into Notification::send.  I think this is working in test because the database is clean and all the ids are 1 - added something to the retro.  Changed to pass the user.
> RES-1621 EventCreated notification sent to wrong place.

- app/Device.php
- app/Group.php
- app/Helpers/LcaStats.php
- app/Http/Controllers/API/EventController.php
- app/Http/Controllers/ApiController.php
- app/Http/Controllers/ExportController.php
- app/Http/Controllers/GroupController.php
- app/Http/Controllers/PartyController.php
- app/Http/Controllers/SearchController.php
- routes/api.php
Fixes issue with numeric 0 estimate values when used in stats calculations.
Included in the fix is a few benign changes to speed up stats calcs when in loops (just sending in the emission ratios to the method so they don't get fetched over and over) and a lot of enhanced comments about stats methods.
> Dat 640 stats estimate zero

- app/Group.php
- app/Services/DiscourseService.php
Change from "Everyone" to "Only group owners, moderators and admins".  Update the setting in the regular sync.
> RES-1617 Change messageable_level on Discourse groups.

- app/Console/Commands/SyncDiscourseGroups.php
- app/Http/Controllers/GroupController.php
- app/Services/DiscourseService.php
Rework the syncing to promote/demote hosts on Restarters w.r.t. owners on Discourse.
Rename the sync method as it's now browser than just users.
> RES-1630 group hosts not owners

- app/Http/Controllers/PartyController.php
- tests/Feature/Events/DeleteEventTest.php
- tests/Unit/Events/TimezoneTest.php
The edit code was missing a key stage in the handling of times, which the create code did correctly.
This is superseded by the later timezone work, but this PR is worth releasing as it beefs up the testing in this area.
> RES-1647 Event edit broken for timezones.

- app/Listeners/LogInToWiki.php
We change the underscore to a dash, but the login hasn't done a `refresh()` and therefore uses the initial username and fails.
> RES-1646 Users with underscores don't get logged in to the wiki immediately

- app/Helpers/Fixometer.php
- app/Http/Controllers/PartyController.php
- app/Party.php
- resources/js/components/EventDescription.vue
- tests/Feature/Events/CreateEventTest.php
- tests/Feature/Events/DeleteEventTest.php
- tests/Feature/Events/InviteEventTest.php
- tests/Feature/Events/JoinEventTest.php
- tests/Feature/Groups/GroupCreateTest.php
- tests/TestCase.php
Add a method for view event permissions.  We should probably be using Laravel gates rather than Fixometer methods - tech debt?
> RES-1627 unapproved events display

- resources/js/components/DashboardYourGroups.vue
It is being used, but not imported.
> RES-1658 fix: import moment

- resources/views/events/view.blade.php
Only added 'finished' and 'upcoming' in https://therestartproject.atlassian.net/browse/RES-1659
More properties may need expanding on the event here.
Not used PartyController::expandEvent here yet as it gives an array, as the later code below looks seems to expect an object.
> RES-1659 Past events not showing repair items

- app/Group.php
- app/Http/Controllers/GroupController.php
- tests/Feature/Groups/GroupDeleteTest.php
We have a check on whether groups are deletable - they're not if they have an event with a device.  But this check, and the code which processes the delete (to delete events, since we don't have cascading foreign keys) was ignoring deleted events.  So the group was showing as deletable but the delete was failing.
> RES-1673 Can't delete a group which has a deleted event.

- app/Party.php
- tests/Feature/Groups/InviteGroupTest.php
We should not notify users of new events if they have been invited to a group but not yet accepted.
> RES-1689 Don't notify users of group events if they are only invited.

- app/Group.php
- app/Http/Controllers/GroupController.php
- app/Party.php
- tests/Feature/Events/CreateEventTest.php
Sorry, bad branch name - this is RES-1675.
Tests and fixes the case for this story, by introducing scopes to use rather than raw queries.  Also fixes another similar but less important case.
The various methods in `Group`, and raw queries which access `groups`/`user_groups`, could benefit from refactoring into scopes in the same way we did with `Party` a while back, but I think that's out of scope (pun intended).
> RES-1685 email notifications

- app/Http/Controllers/ApiController.php
- app/Http/Controllers/GroupController.php
- app/Http/Controllers/PartyController.php
- app/Listeners/CreateDiscourseThreadForEvent.php
- routes/web.php
- tests/Feature/Events/AttendanceTest.php
- tests/Feature/Events/ModerationEventPhotosNotificationTest.php
- tests/Feature/Groups/GroupEditTest.php
- tests/Feature/Stats/EventStatsTest.php
- tests/Feature/Stats/GroupStatsTest.php
1. Fix a Sentry error caused by getting stats for an invalid group id.
2. Fix a Sentry error creating Discourse thread.
3. Remove dead code for `get-group-emails` which is not used - probably superceded by `get-group-emails-with-names`.
4. Add extra tests for coverage.
> RES-1687 sentry

- resources/views/landing.blade.php
- tests/Feature/Home/HomeTest.php
Added the language bar into the landing page blade explicitly, rather than messing with the layout, in case that breaks other things.  We also need the JS.
Also moved the CSS in the landing page, because I've noticed that if you refresh, you see one of the small icons at an enormous size until it loads the `<style>` section lower.  Moving it up stops that.
> RES-1688 landing page language

- app/Http/Controllers/GroupController.php
- resources/js/components/GroupEvents.vue
- tests/Feature/Groups/GroupViewTest.php
The group page claims to show upcoming and active events, but in fact only shows upcoming.
> RES-1700 In progress events not showing on group page.

- app/Notifications/NewDiscourseMember.php
- app/Notifications/RSVPEvent.php
Was `email_preference` rather than `email_preferences`.
I don't think it's worth adding a test for the text in this case..  We are considering revamping notifications, and if we did that, then we might want to introduce standard headers and footers which are set in a single base notification class.
> RES-1729 typo in email preference string

- resources/js/misc/notifications.js
I think the classes changed, so I've fixed the jQuery selector.
In the longer term this code should die and be replaced with an API call.  So I've not bothered fixing the very minor issue that if you have > 99 unread notifications, and you mark one as read, then it'll show 98 whereas it should really still show 99 (and would on a refresh)..
> RES-1726 Notification counts wrong when marking notifications as read

- app/Faultcat.php
- app/Http/Controllers/API/NetworkController.php
- app/Http/Resources/PartySummary.php
- app/Mobifix.php
- app/Party.php
- routes/api.php
- tests/Feature/Networks/APIv2NetworkTest.php
1. Add an endpoint to list events of a network.
2. Add `updated_start` and `updated_end` to that plus listing the groups of a network.
3. Possible fix for some test flakiness - add an extra ORDER BY to query on fault opinions to make it deterministic in cases where there are equal numbers of opinions.
> RES-1723 new API endpoints

- resources/js/components/EventPage.vue
The client side code tries to deal with attendees as a single list with a flag that says whether they are confirmed.  The server passes back two lists, and the client forgot to use the invited one.
> RES-1751 Invited attendees missing from event

- resources/js/components/GroupsTable.vue
This is unrelated to the previous case.
Until we make more progress on using an API, we pass data via props.  This means that we don't get the full benefit of a reactive store - in cases like this we'd leave the group, remove it from the store, and then the table would update.  I've added a workaround for now, as moving to an API for our list of groups is a bit bigger than this bug can support.
> RES-1746 Group still shows after leaving until refresh

- .circleci/config.yml
- app/Helpers/FixometerFile.php
- app/Http/Controllers/DeviceController.php
- app/Xref.php
- resources/js/components/DeviceImage.vue
- resources/js/components/DeviceImages.vue
- resources/js/components/EventDevice.vue
- resources/js/components/EventDeviceSummary.vue
- resources/js/components/FileUploader.vue
- resources/js/store/devices.js
- resources/lang/en/devices.php
- resources/lang/fr-BE/devices.php
- resources/lang/fr-BE/notifications.php
- resources/lang/fr/devices.php
- resources/lang/fr/notifications.php
- routes/web.php
- tests/Feature/Devices/EditTest.php
- tests/Integration/device.test.js
- tests/Integration/utils.js
- tests/Unit/NotificationsTest.php
When we implemented the new design, we deferred adding photos until the item was created.  This fixes that.
When we are in the Add flow, we upload images using a unique negative device id.  Then when we add the device, we attach those photos to the correct device id.  
Because when we're adding we might be adding multiple copies of the device, we copy the image file.  This means we have potentially multiple copies of the same photo.  I considered having a single copy with references to it, but that's a bit complex, and this whole Xref area is ripe for some improvement anyway.  For similar reasons I don't delete the underlying file when we delete a photo from a device - that's rare.
Also:
- Restrict uploads to image files.
- Add a limit of 5 photos.
- Resize files on client to a max of …
> RES-1345 upload photos

- app/Http/Controllers/GroupController.php
- app/Http/Controllers/PartyController.php
- resources/js/components/GroupTimeZone.vue
- resources/lang/en/partials.php
- resources/lang/fr-BE/partials.php
- resources/lang/fr/partials.php
- tests/Unit/Events/TimezoneTest.php
This protects against invalid timezones on the server side.
It provides a visual indicate when the timezone is invalid on the client side.  This isn't perfect, because you can still submit an invalid one and hence get the server error.  But it's hard to do much better until we convert that create form to Vue.
> RES-1769 Firewall against invalid timezones

- app/Http/Controllers/GroupController.php
- app/Http/Controllers/PartyController.php
- tests/Feature/Events/InviteEventTest.php
- tests/Feature/Groups/InviteGroupTest.php
This checks that emails are valid when we invite to groups/events.
As with many error messages, the error text is not translated.  This isn't great, but I want to get this one in quickly because of the system impact.
> RES-1770 Firewall invalid emails

- app/Network.php
- tests/Unit/Events/CoordinatorTest.php
Promote to network coordinator when adding.  Don't demote.
> RES-1761 Network coordinator artisan command doesn't set role

- app/Console/Commands/ImportMRES.php
- app/Console/Commands/UserCreate.php
- app/Console/Commands/UserMakeHost.php
- app/Notifications/ResetPassword.php
- app/Services/DiscourseService.php
- app/User.php
- tests/Feature/Groups/GroupCreateTest.php
- tests/Feature/Networks/NetworkCommandsTest.php
- tests/Feature/Users/UserCommandsTest.php
- tests/TestCase.php
- tests/Unit/NotificationsTest.php
1. Add a command to create a user.  When they next log in (possibly after a password reset) then they'll get prompted to go through filling out the remaining details we need.
2. Add a command to make a user a host.
3. In the MRES import job, spit out a command script containing these two commands.
> RES-1736 Add commands to create hosts for MRES

- app/Http/Resources/Group.php
- app/Http/Resources/GroupLocation.php
- app/Http/Resources/GroupSummary.php
- tests/Feature/Groups/APIv2GroupTest.php
- tests/Feature/Networks/APIv2NetworkTest.php
Add the `area`, `location` and `country` fields to the group summary.
> RES-1790 Add group location to API call

- app/Http/Controllers/NetworkController.php
- app/Network.php
- composer.json
- composer.lock
- config/croppa.php
- config/filesystems.php
- database/migrations/2022_10_06_162442_network_logo.php
- resources/views/networks/index.blade.php
- resources/views/networks/show.blade.php
- tests/Feature/Groups/BasicTest.php
- tests/TestCase.php
1. Add a `logo` column to the `networks` table to store the file path, and migrate the data over.
2. Upload files in NetworkController using `store()`, which is more idiomatic.
3. Put them in `public_uploads/network_logos`, by creating a disk for that in `filesystems.php` and passing a path to `store()`.
4. Change the `logo()` method to generate the appropriate path for Croppa, which will handle generating and caching different sizes as required.
5. Increase logos from 50px to 100px - retina screens means that probably too low res nowadays.
6. Fix a bug in the test, where the regex was greedy and shouldn't be.
> RES-1760 remove xref

- app/Http/Controllers/PartyController.php
`expandEvent` was using the count of named volunteers rather than the separate volunteer count.
> RES-1784 Value for number of repairers in event listings doesn't match value set against event

- resources/js/components/GroupEventScrollTable.vue
We use a custom sort function for the events table; make it aware of the past.
There's a very slight confusion which could arise because of the arrows on the sort table.  You might think that the arrows should start with a different one selected on the two different tabs.  They don't.  But I think anyone who uses these arrows to change the sort direction will basically treat them as a toggle without much thought as to what they mean.
> RES-1785 Show past events most recent first

- playwright.config.js
- resources/js/components/DeviceRepairStatus.vue
- resources/js/components/EventDevice.vue
- resources/js/components/EventDeviceSummary.vue
- tests/Integration/device.test.js
- tests/Integration/utils.js
I think the scenario here is that you create an item, mark it as Fixed, but leave the spare parts field untouched.  
Logic doesn't handle the 0/null case of the `spare_parts` field, resulting in it wrongly selecting the last option.
> RES-1783 Edit a newly created fixed item, spare parts field value changed

- app/Http/Controllers/API/NetworkController.php
- app/Http/Resources/PartyCollection.php
- app/Network.php
- resources/views/networks/index.blade.php
- resources/views/networks/show.blade.php
- tests/Feature/Networks/APIv2NetworkTest.php
Generally the API should return quickly and without too much data, suitable for a web client.  But for networks, the API may be used for background bulk operations where it's more convenient to fetch the details in a single call.  
This PR adds an `includeDetails` parameter to allow this.
> RES-1808 Add includeDetails parameter to network API

- app/Http/Resources/Network.php
- app/Http/Resources/NetworkSummary.php
- resources/js/components/GroupDevicesBreakdown.vue
- resources/sass/_events.scss
- tests/Feature/Networks/APIv2NetworkTest.php
Since we changed the way in which the image uploads work, we just need to return the string value of the path now.
> RES 1811 Fix return value for network logo path

- app/Http/Controllers/DeviceController.php
- resources/js/components/EventDevice.vue
- resources/js/store/devices.js
This adds a validation on the server side so that an exception is thrown if the age is > 500 years on device add/edit.  This should trigger an exception which we will see in Sentry.
Added something to ensure that these errors get displayed on the client side.
There is a different kind of validation code on the server which returns a success with some information.  I think that code is now dead, but it will get removed when we convert this to an API call, so I'm ignoring it for now.
> RES-1820 Ensure age is not older than 500 years

- resources/wiki/css/app.scss
The wiki CSS has some code which overrides styles in the collapsible section. This seems to be wrong for our purposes - perhaps the overall style has changed and this didn't get updated.
> RES-1822 wiki collapsible section

- resources/js/components/EventAddEdit.vue
The code is using `slice()` rather than getting the date correctly using the timezone.
> RES-1846 Event date is wrong when editing in some timezones

- config/queue.php
- resources/views/partials/visualisations/consume.blade.php
- resources/views/partials/visualisations/manufacture.blade.php
Fix the queue configuration to use database by default.  Also fix up a couple of cases where we call `Str::plural` with a string, which now causes PHP warnings.
> RES-1835 Fix queueing configuration

- app/Http/Controllers/API/GroupController.php
- app/Http/Controllers/ApiController.php
- app/Http/Controllers/PartyController.php
- app/Rules/Timezone.php
- tests/Feature/Groups/APIv2GroupTest.php
- tests/Feature/Groups/GroupEditTest.php
Some timezones, e.g. Australia/Canberra, are "outdated", and not returned by PHP by default.  We had an inconsistency - we grabbed a list of timezones from MySQL, but then validated it using the PHP list.
It's arguable which we should use, but we should definitely be consistent.  I think we should use the PHP list, because if it doesn't work in MySQL then it should - it's a MySQL config issue.
> RES-1856 Allow "outdated" timezones

- app/Http/Controllers/DashboardController.php
Use a max of 5 for groups and upcoming events.
> RES-1849 Make number of events/groups shown on dashboard have a consistent max

- app/Http/Controllers/API/EventController.php
- app/Http/Controllers/API/GroupController.php
- app/Http/Controllers/API/NetworkController.php
- app/Http/Resources/Group.php
- app/Http/Resources/GroupCollection.php
- app/Http/Resources/GroupLocation.php
- app/Http/Resources/GroupSummary.php
- app/Http/Resources/GroupSummaryCollection.php
- app/Http/Resources/Network.php
- app/Http/Resources/NetworkSummary.php
- app/Http/Resources/NetworkSummaryCollection.php
- app/Http/Resources/Party.php
- app/Http/Resources/PartyCollection.php
- app/Http/Resources/PartySummary.php
- app/Http/Resources/PartySummaryCollection.php
- app/Http/Resources/Tag.php
- app/Http/Resources/TagCollection.php
- composer.json
- composer.lock
- resources/js/store/events.js
- resources/js/store/groups.js
- tests/Feature/Events/APIv2EventTest.php
- tests/TestCase.php
This builds in automatic testing of the OpenAPI specification to our tests.  
We have some cases where we use `anyOf` to return a group/group summary or similar.  For the code to work out which one it is and validate it, we need to add in fields which force the models to be different (not just a subset) and make it required.
Fixes quite a fix issues with the way the API was documented which I hadn't noticed.
> RES-1843 Add OpenAPI coverage testing

- app/Http/Controllers/PartyController.php
- app/Party.php
The upcoming events on the dashboard are appearing in an odd order.  This is because we have a default ORDER BY introduced by `scopeUndeleted`, but when that is then used indirectly via other scopes which do a `union`, the order doesn't get applied to the overall query.
Eloquent is in a bit of a guddle over this. There is a `reorder() ` method which you can use to strip out earlier ORDER BY clauses in order to replace it with your own.  But this method doesn't seem to play nice with union queries, so it doesn't fully work for the case we want.
So I've changed one of the scopes to use `reorder` earlier enough so that it works, and then impose the order again in a parent scope.
There are times when it feels like writing raw queries is a lot easier.
> RES-1880 Ordering of events on dashboard

- app/Http/Controllers/API/GroupController.php
- app/Http/Controllers/GroupController.php
- resources/views/group/index.blade.php
- tests/Feature/Groups/BasicTest.php
- tests/Feature/Groups/GroupCreateTest.php
Restarters should be able to create groups.  Allow them to do so, and promote to a host if required.
> RES-1867 Allow restarters to create groups

- resources/js/components/DashboardBanner.vue
To appear first thing Thursday 20th April, and be removed last thing on Thursday 27th April.
> RES-1889 Set up dashboardbanner for Big Give 2023

- app/Http/Controllers/DeviceController.php
- tests/Feature/Devices/CategoryTest.php
Bad code in `ajaxEdit`.  Add a test, and make it work.
> RES-1888 Category_creation field shouldn't be changed when editing a device

- app/Http/Resources/Group.php
- lang/en/networks.php
- lang/fr-BE/networks.php
- lang/fr/networks.php
- resources/js/components/GroupAddEdit.vue
- resources/js/components/NetworkData.vue
- resources/js/components/NetworkDataField.vue
- resources/views/partials/log-accordion.blade.php
We have a `network_data` field for groups.  This is JSON-encoded.  This PR exposes editing of that for network coordinators on the groups page.
A separate text input is created with a suitable label for each entry in the JSON object.  
There's a button to allow you to add a new (empty) entry, which effectively allows you to extend the schema.  You can't delete them, though, as that is a bit dangerous.
I've done this for groups only, though we may choose to extend it to events too.
> RES-1892 Add ability to edit network data for groups.

- app/Console/Commands/SyncDiscourseUsernames.php
I'm not sure if this is due to a change in Discourse behaviour, but the API is no longer returning the email address.  However it does return the external (i.e. Restarters) id, so we can use that instead.
> RES-1866 Discourse usernames not syncing

- resources/views/networks/show.blade.php
Change the network description so that if the description is short enough not to need truncation, then we insert it as HTML rather than stripping the tags.  This allows the Cambridgeshire Metabase link to be inserted, as long as we use a tinyurl version of it.
This is messy, but this page needs Vueification, so I don't think it's worth investing too much time in it.
> RES-1898 Add Cambridge Metabase Dashboard link

- app/Http/Controllers/UserController.php
- tests/Feature/Events/AddRemoveVolunteerTest.php
- tests/Feature/Events/InviteEventTest.php
- tests/Feature/Networks/NetworkTest.php
- tests/TestCase.php
When we demote someone from a role of network coordinator, we should remove them from any networks they are currently coordinating.
Some test fiddling to make it easier to run them in isolation.
> RES-1906 Demote network coordinator

- app/Listeners/EditWordpressPostForEvent.php
- tests/Feature/Events/WordpressEventPushTest.php
`EditWordpressPostForEvent` is looking in the data passed to the (Laravel) event for the id of the group.  That isn't always present, and doesn't need to be because we have the (Restarters) event in hand and can pull the group from there.
> RES-1926 Event handler is looking for data which doesn't get passed

- resources/js/mixins/event.js
This is because we failed to set the locale when getting the month (and also day of month).  The locale will get set later, inside the `date` computed, which means that for subsequent rows in the table we'll be using the correct locale.
> RES-1927 First month in events table is not translated

- resources/js/components/EventAddEdit.vue
- resources/js/components/EventAddEditPage.vue
Recent changes to use the API for event creation left event duplication confusing.  The duplicate was created, but the user was left on the same page and understandably thought that the duplicate hadn't been made.
This PR ensures that the page URL is updated correctly, that the page title is updated, and that we display the new event in edit mode.
Some of this is working around the fact that we don't have a genuine SPA.
> RES-1928 Event duplication is confusing

- resources/js/components/CollapsibleSection.vue
- resources/js/components/EventDeviceList.vue
- resources/js/components/EventDeviceSummary.vue
- resources/js/components/EventDevices.vue
The device table on mobile has a number of display issues.
> RES-1933 mobile layout when viewing data

- app/Http/Controllers/API/EventController.php
* Extend the allowed process length for this particular method.
* Fix error with inclusion of Carbon when date parameters have been provided.
> RES-1937 Avoid all events API timeout

- app/Console/Commands/ImportMRES.php
- app/Group.php
- app/Http/Controllers/API/GroupController.php
- app/Http/Resources/Group.php
- database/migrations/2023_08_14_112539_group_email.php
- lang/en/groups.php
- lang/fr-BE/groups.php
- lang/fr/groups.php
- resources/js/components/GroupAddEdit.vue
- resources/js/components/GroupDescription.vue
- resources/js/components/GroupEmail.vue
- tests/Feature/Groups/APIv2GroupTest.php
- tests/Feature/Groups/GroupEditTest.php
- tests/TestCase.php
1. Add migration for group email property.
2. Add script to set this for MRES groups.  Note that a few mismatch and will need to be set by hand.
3. Add email to the API, and test it.
4. Change client to expose email in group add/edit.
5. Rejig group edit layout to make it neater, including mobile.
6. Tweak translations a little bit to make the layout fit.
> RES-1917 group email

- resources/js/components/EventDevice.vue
The weight field doesn't always show (intentionally) and this can cause the position of the age field to move around.  Move the weight field down so that this inconsistency doesn't happen.
> RES-1934 Make age field always appear in a consistent position

- app/Http/Resources/Group.php
- app/Http/Resources/Party.php
- tests/Feature/Events/APIv2EventTest.php
- tests/Feature/Groups/APIv2GroupTest.php
In the DB, we have some groups with `network_data` set to `"[]"`.  The server will encode this up into JSON, and then on the client side this will be an array not (as expected) an object.  That means when we set new network data values, they're not saved properly.
This fix strips out the `network_data` field from the API if it is of type array, and returns null instead.  The client will then default the network data to `{}`, an object, which works correctly.
> RES-1941 Changes to network data on groups not persisting

- app/Console/Commands/FixVolunteerCount.php
- app/Http/Controllers/PartyController.php
- app/Observers/EventsUsersObserver.php
- resources/js/components/EventAttendanceCount.vue
- tests/Feature/Events/AddRemoveVolunteerTest.php
- tests/Feature/Events/InviteEventTest.php
- tests/Feature/Events/JoinEventTest.php
It's possible to end up with a negative attendee count, probably accidentally:
- Have a positive one.
- Type "-" in the box.
This PR firewalls against setting and showing negative values.
There are also cases in `EventsUsersObserver` which can cause this, especially relating to invitations.
> RES-1942 Negative attendee count

- resources/js/components/EventAddEdit.vue
Approval is working, but the approve dropdown shouldn't show once the event has been approved.  Make sure we set our local flag that controls this from the event data.
> RES-1940 Approve dropdown wrongly showing for events after approval

- app/Console/Commands/CrystalliseEventTimezone.php
- app/Console/Kernel.php
- tests/Unit/Events/TimezoneTest.php
Add a scheduled job which sets the timezone on events explicitly once they've passed.  This avoids the potential problem where groups change timezone later.  It also helps with some Metabase reports.
> RES-1929 Crystallise timezone on past events

- lang/en/events.php
- lang/en/groups.php
- lang/fr-BE/events.php
- lang/fr-BE/groups.php
- lang/fr/events.php
- lang/fr/groups.php
- lang/no/groups.php
- resources/js/components/GroupAddEdit.vue
- resources/js/components/GroupLocation.vue
- resources/js/components/VenueAddress.vue
If the value entered is not geocodable, then we leave the old values in place and so the change appears to work but is lost.
This fettles use of `vue-auto-complete` so that we will reset the values to null (therefore invalid) until a valid geocoded result is given.
It's perhaps not obvious that you need to select one from the dropdown list.  I think people will realise that, but please consider whether or not we need a text change.
> RES-1944 group location not persisted

- app/Http/Controllers/GroupController.php
- app/Party.php
- lang/en/groups.php
- lang/fr-BE/groups.php
- lang/fr/groups.php
- resources/js/components/GroupDevicesBreakdownCluster.vue
- resources/views/group/view.blade.php
Two things here:
1. The total used in `GroupDevicesBreakdownCluster` is not the total within that cluster.  It's not completely clear what it actually is, but it's not what we need.  So fix that.
2.  The use of object literals in the `$template` variable is causing the different clusters to all share the same underlaying object.  That wasn't the intention and isn't obvious.  This results in all the clusters are being given the same values.  Scrap the object stuff and just use an associative array here and in the template where we retrieve it.
> Group stats percentages are wrong

- resources/js/components/DashboardBanner.vue
> RES-1954 Add banner for Aviva crowdfunder

- app/Listeners/AddUserToDiscourseThreadForEvent.php
Our externally hosted Discourse is misbehaving.  If API requests take a long time, it can block the Laravel queue handler, which then times out and exits.
This PR is a hack to keep the queue functional.
> RES-1956 Discourse problems blocking queue handler

- app/Http/Controllers/DeviceController.php
- tests/Feature/Devices/EditTest.php
- tests/TestCase.php
A local loop variable was overwriting the input value, which only showed up when we made multiple passes through to create multiple devices.
> RES-1968 Can't create multiple devices with a barrier to entry

- resources/js/components/StatsShareModal.vue
Looks like `emHeightAscent` and `emHeightDescent` don't work on older browsers.  Switch to `actualBoundingBoxAscent` and `actualBoundingBoxDescent`.
> RES-1973 Sharable stats aren't rendered properly on older browsers

- app/Http/Controllers/DashboardController.php
- resources/js/components/DashboardPage.vue
- resources/js/components/DashboardYourGroups.vue
Check whether we have the host role on at least one group before showing the Add event button on the dashboard.
> RES-1971 Only show Add Event button on Dashboard when the user is a host

- app/Http/Controllers/API/AlertController.php
- app/Http/Controllers/API/EventController.php
- app/Http/Controllers/GroupController.php
- app/Http/Controllers/PartyController.php
- composer.json
- composer.lock
- tests/Feature/Alerts/AlertsTest.php
- tests/Feature/Events/CreateEventTest.php
- tests/Feature/Events/InviteEventTest.php
- tests/Feature/Groups/InviteGroupTest.php
- tests/TestCase.php
We've seen disk full caused by repeated retrying of email notifications to an invalid email address.  This is where someone puts in a name instead of an email address.
We should prevent that in the front end, but that code is not yet in Vue. This fix introduces better validation of email addresses on the server side.
Also fixes DST issues in Alerts code.
> RES-1974 Validate email addresses in invitations

- resources/js/components/StatsShare.vue
Older browsers (e.g. Firefox 89) don't support `roundRect` or `emHeight*`.  Add some backwards compatibility.
> RES-1973 Older browsers not rendering stats correctly

- app/Http/Controllers/API/EventController.php
- tests/Feature/Events/AddRemoveVolunteerTest.php
The new API code wrongly assumed that the volunteer email address would always be provided.
> RES-1983 Can't add volunteer to past events

- app/Listeners/DeviceUpdatedAt.php
- tests/Feature/Devices/EditTest.php
What looks to have happened here is:
- Event created
- Device updated, generating queue job
- Event deleted before queued job is processed
- Queued job then throws and exception
- This retries a lot, causing some disk full
> Stuck queue job for deleted event

- app/Http/Controllers/GroupController.php
- resources/views/group/edit.blade.php
- tests/Feature/Groups/GroupEditTest.php
…for groups which are not in their network.
This will include groups which they have just created, unless they have a custom domain and the groups are auto-approved.
> RES-1984 Network Coordinator shouldn't see approval option

- app/Console/Commands/WordpressCreateEventFailed.php
- app/Console/Kernel.php
In some error cases events can fail to be created on the Wordpress side.  This provides a scheduled command as a fallback to find and create them.
> RES-1969 Fallback scheduled job to create missing Wordpress events

- app/Services/DiscourseService.php
Seen on the live system after a Discourse upgrade.
> RES-1989 Discourse API for adding group owners has changed

- app/Http/Controllers/GroupController.php
This is because there are too many audit logs.  Change this to only return the very recent logs.  We will consider how to display logs better overall elsewhere.
> RES-2009 Can't edit Southampton group page.

- app/Http/Controllers/API/GroupController.php
- tests/Feature/Groups/GroupHostTest.php
The function to change the role of a member to Host was lost in recent API changes.  This restores it and adds a test.
> RES-2015 Host can't create event

- app/Providers/DiscourseServiceProvider.php
Add timeouts to use of Guzzle against Discourse hosting so that PHP script timeout doesn't kick in.
> RES-2010 Communiteq problems blocks event approval

- app/Http/Controllers/API/EventController.php
- tests/Feature/Events/CreateEventTest.php
For new events, don't notify admins who are also network coordinators if they have turned that setting off.
> RES-2021 Don't notify admins who are also network coordinators of events

- resources/js/components/EventDevice.vue
- resources/js/store/devices.js
This was lost in recent API changes.
It's not immediately clear why the `JSON.parse` and setting of `eventid` is necessary, but it will be a consequence of reactive changes from the store, and this works.
> RES-2019 Reinstate function to add multiple items.

- database/migrations/2025_04_14_093813_missing_primary_keys.php
This is good practice anyway, and Digital Ocean doesn't like databases which don't have them.
> RES-2028 Add primary keys to tables which don't have them
