TheRestartProject/restarters.net

app/Notifications/AdminNewUser.php
changed the url for notifications and email
=> changed the url to view profile

resources/views/reporting/time-volunteered.blade.php
changed the class from container-fluid to container
=> edited the class

resources/views/skills/edit.blade.php
deleted the class="rte" from the textarea.
=> deleted the class related to summer-note

resources/views/dashboard/blocks/discussion.blade.php
deleted the heading -Discussion
=> deleted the heading

resources/views/auth/forgot-password.blade.php
=> added a new div and class

resources/views/group/view.blade.php
deleted the area from the view blade of the groups
=> deleted the area

resources/lang/en/event-audits.php, resources/lang/en/group-audits.php
added the wordpress key for events and groups lang files
=> added the key in lang files

app/Helpers/FixometerFile.php, app/Http/Controllers/GroupController.php
Handle failed image uploads gracefully & later on in group creation process; Show groups under "Your groups" even if no events are in the database
=> Error sometimes occurring when creating a group

app/Faultcat.php, app/Http/Controllers/FaultcatController.php, resources/views/faultcat/index.blade.php, resources/views/faultcat/shared-css.blade.php, resources/views/faultcat/status.blade.php, routes/web.php
As per MiscCat
restarters.net/faultcat/status
=> Adds FaultCat status page

app/Misccat.php, resources/views/misccat/status.blade.php
Refactors misccat/status query grouping
Removes redundant columns from view tables
=> Misccat status

app/Http/Controllers/MobifixController.php, resources/views/mobifix/index.blade.php, resources/views/mobifix/shared-css.blade.php
Routes, migration, controllers, views etc. for new microtask MobiFix
=> Adds microtask MobiFix

app/Http/Controllers/MobifixController.php, resources/views/mobifix/index.blade.php, resources/views/mobifix/shared-css.blade.php
Adds tooltips to fault type buttons in MobiFix app
=> Adds tooltips to Mobifix

app/Console/Commands/FixLatitudeLongitude.php
Look for lat/lngs which are probably bad and re-geocode the location to fix them.
=> DOT-1268 Command to fix up bad latitudes and longitudes

app/Console/Commands/SyncFaultTypes.php, app/Faultcat.php, app/Http/Controllers/MobifixController.php, app/Mobifix.php, resources/views/mobifix/index.blade.php, resources/views/mobifix/status.blade.php, tests/Unit/FaultcatTest.php, tests/Unit/MobifixTest.php
Redirects to mobifix/status with message when there are no more records to fetch
Implements default status message when Mobifix task is complete
Hides 3-2-1 opinions counter when Mobifix task is complete
=> Implements handling for Mobifix completion

features/14-Microtasks/Faultcat.feature, features/14-Microtasks/Misccat.feature, features/14-Microtasks/Mobifix.feature, features/14-Microtasks/MobifixOra.feature, tests/Feature/Microtasks/FaultcatTest.php, tests/Feature/Microtasks/MisccatTest.php, tests/Feature/Microtasks/MobifixOraTest.php, tests/Feature/Microtasks/MobifixTest.php
Adds Microtask features and moves Microtask tests from Unit to Features
=> Fixes DAT-328

resources/views/events/view.blade.php
500 error if trying to view an event without logging in.  Need to check Auth::user() before dereferencing it.
=> Can't view event logged out

app/Http/Controllers/PartyController.php, resources/assets/js/app.js, resources/assets/js/components/GroupEvents.vue, resources/assets/js/components/GroupEventsPage.vue, resources/assets/js/store/events.js, resources/views/events/index.blade.php
This page got broken when I created GroupPage.vue.
=> Group events page is empty

package-lock.json, package.json, resources/assets/js/components/GroupEvents.vue
=> Speed up event page using infinite scroll

resources/assets/js/app.js, resources/views/auth/register-new.blade.php
There is an error message already in the DOM, but no code to show it.  Added some.
=> DOT 1349 bad password help

app/Http/Controllers/MobifixOraController.php, app/MobifixOra.php, resources/views/mobifixora/index.blade.php
Found a bug in MobiFix:ORA form submission that allowed duplicate submits after certain sequence of actions, also allowing fault_type_id=0 to be submitted.
=> Fixes MobiFix:ORA form submit bug

package-lock.json, package.json
=> Bump axios from 0.19.2 to 0.21.1

resources/assets/js/components/EventAttendance.vue, resources/assets/js/mixins/event.js
Bit of confusion about where the count was.
=> DOT-1382 Volunteer count warning wrong

app/Http/Controllers/ExportController.php, resources/assets/js/components/FixometerPage.vue, resources/views/fixometer/index.blade.php
I broke this when removing code I thought was dead.  The old code used DeviceController::search, which no longer exists.  
I'm not sure that's necessary or the best way to do it.  Can you think about whether there is any reason not to return all the devices?
=> DOT-1383 Fix export

resources/lang/en/devices.php
The tooltip was missing because it wasn't there.
=> DOT-1388 Missing tooltip

app/Http/Controllers/DeviceController.php, resources/assets/js/components/EventPage.vue, resources/views/fixometer/add-data-modal.blade.php, resources/views/fixometer/index.blade.php
As discussed, the modal already exists and (pretty much) works if we insert it.
=> DOT-1391 Insert modal for Add Data

resources/lang/en/devices.php, resources/views/fixometer/add-data-modal.blade.php
=> DOT-1406 Add labels for add data modal

resources/assets/js/components/DashboardGroup.vue
=> DOT-1423 follow group

resources/assets/js/components/DashboardEvent.vue, resources/assets/js/components/EventHeading.vue, resources/assets/js/components/EventTitle.vue, resources/assets/js/components/GroupEventSummary.vue, resources/lang/en/events.php
Introduce an EventTitle component which shows a badge when the event is online.
The eslint disable is to prevent IDEs (like mine) auto-formatting the HTML in a way that introduces a space, which then becomes part of the link and gets underlined.
=> DOT-1413 online event badge

resources/assets/js/components/GroupEvents.vue
Sort upcoming events into soonest first, past events into most recent first.
=> DOT-1425 Sort events in sensible order

app/Http/Controllers/API/EventController.php, app/Http/Controllers/API/GroupController.php, app/Http/Controllers/ApiController.php, app/Http/Controllers/GroupController.php, app/Http/Controllers/PartyController.php
Return the area code on group/event API calls.
=> DOT-1418 area info

.circleci/config.yml, .env.example, README.md, composer.json, composer.lock, phpunit.xml, resources/views/group/edit.blade.php
I've made some changes which get one of the existing tests running.
There's lots more to do here, but this is the first step.
=> DOT-1440 Circle-CI

.circleci/config.yml, README.md, app/Http/Controllers/DeviceController.php, app/Providers/AppServiceProvider.php, database/migrations/2021_05_14_173108_repairdir_role.php, phpunit.xml, tests/Feature/Dashboard/BasicTest.php, tests/Feature/Fixometer/BasicTest.php, tests/Feature/Groups/BasicTest.php, tests/Feature/Groups/GroupCreateTest.php, tests/Feature/Microtasks/BasicTest.php, tests/Feature/Users/Registration/AccountCreationTest.php, tests/Feature/Users/Registration/DiscourseAccountCreationTests.php, tests/TestCase.php
Add some very very basic tests.
I've started to add some utility methods inside TestCase so that we don't duplicate code to e.g. create a user or a group.
I had to make a couple of minor fixes to get this to run - you'll see them in the diffs.
=> DOT-1446 regression

app/Console/Commands/SetPostcodes.php, app/Helpers/Geocoder.php
Add artisan command to set missing postcodes.
=> DOT-1433 postcode setup

app/Device.php, app/Events/DeviceCreatedOrUpdated.php, app/Group.php, app/Http/Controllers/API/EventController.php, app/Http/Controllers/API/GroupController.php, app/Http/Controllers/DeviceController.php, app/Listeners/DeviceUpdatedAt.php, app/Party.php, app/Providers/EventServiceProvider.php, database/migrations/2021_05_14_105028_devices_updated_at.php
This introduces an event for devices being created/updated, listens on it, and uses that to maintain a devices_updated_at field in the party and group.
=> DOT-1369 groups events devices update

resources/views/tabicatora/index.blade.php
so that it is not hidden by the bottom nav
=> Moves TabiCat's "Go with" button up

resources/views/tabicatora/index.blade.php
Also fixes TabiCat sending bad string to Google translate
=> Hides TabiCat "Translate" button when user language == problem language

resources/views/tabicatora/status.blade.php
=> DAT-549 tabicat status fault types

.circleci/config.yml, app/Http/Controllers/ApiController.php, app/Http/Controllers/PartyController.php, phpunit.xml, tests/Feature/Events/CreateEventTest.php, tests/Feature/Events/DeleteEventTests.php, tests/Feature/Events/EventRequestReviewEmailTest.php, tests/Feature/Events/ModerationEventPhotosNotificationTest.php, tests/Feature/Events/OnlineEventsTests.php, tests/Feature/Events/WordpressEventPushTest.php, tests/TestCase.php
Get a few more existing tests working.  Coverage now 16%.
=> DOT-1459 add tests

app/Http/Controllers/GroupController.php, resources/lang/en/groups.php, tests/Feature/Groups/GroupCreateTest.php
Return a meaningful error if you try to create a group that already exists.
=> DOT-1473 duplicate group creation

app/BattcatOra.php, tests/Feature/Microtasks/BattcatOraTest.php
=> Dat 567 battcat status page

app/Http/Controllers/BattcatOraController.php, resources/views/battcatora/index.blade.php, resources/views/battcatora/task-survey-modal.blade.php
Also replaces survey redirects to Tabicat with Battcat redirects
=> Removes signposting code from Battcat controller and view

resources/js/components/MicrotaskingVolunteering.vue, resources/lang/en/microtasking.php
Also include TabiCat in open quests.
=> Add BattCat (configurably) as the Workbench CTA.

app/Console/Commands/SyncDiscourseUsernames.php, app/Services/DiscourseService.php, docker-compose.yml, tests/Feature/Users/Registration/DiscourseAccountCreationTests.php
Retire use of a deprecated call.
=> DOT-1504 deprecated Discourse call

app/Http/Controllers/PartyController.php, tests/Feature/Events/CreateEventTest.php
Test and ensure that we don't send duplicate notifications for event creation.
=> DOT-1514 duplicate notifications

app/Providers/OurSentryLogging.php, app/Services/DiscourseService.php, config/app.php
Listen on logs and pass errors to Sentry.  
Fixed an example of that which I see in dev.
=> DOT-1494 more sentry logging

resources/js/components/VenueAddress.vue
We've seen this in Sentry.  It's benign.
=> DOT-1542 Sentry errror when adding events

app/Http/Controllers/DashboardController.php, resources/js/components/DashboardEvent.vue, tests/Feature/Dashboard/BasicTest.php
The logic in the dashboard for which events to show was wrong.  Fix it.
I've added a basic test for this.  I've not included a test for the actual case which failed (events too far away) since the code no longer pays attention to that, and so it doesn't feel worth while.
=> DOT-1527 dashboard upcoming events

resources/js/components/DashboardNoGroups.vue, resources/js/components/DashboardYourGroups.vue, resources/lang/en/dashboard.php, resources/views/user/profile/calendars.blade.php
Add a link to the nearby section, and make the link styles consistent within this section.
=> DOT-1534 All all groups link to nearby groups.

app/BattcatOra.php, app/Misccat.php, app/MobifixOra.php, app/PrintcatOra.php, app/TabicatOra.php, tests/Feature/Microtasks/ExampleTest.php, tests/Feature/Microtasks/MisccatTest.php
Removes calls to ANY_VALUE() from raw sql (in microtask code)
=> Dat 595 mysql any value

app/Group.php, app/Http/Controllers/GroupController.php, resources/js/components/GroupsTable.vue, tests/Feature/Groups/InviteGroupTest.php
The groups table was using counts which included unconfirmed hosts/volunteers.  
I've made a conservative fix which preserves the existing values and adds new counts for the confirmed values.
=> RES-1585 number of volunteers

app/Helpers/Fixometer.php, tests/Feature/Events/DeleteEventTest.php
Change the permissions model a bit, and test.
=> RES-1605 Allow hosts to delete their erroneous events.

app/Search.php, tests/Feature/Events/ExportTest.php
This is down to an Eloquent query which is trampling on the group id when the group has a tag.
=> RES-1584 Events export is missing group name.

app/Http/Controllers/GroupController.php, tests/Feature/Groups/BasicTest.php
Distance calculation returns NAN if the user and group are at the same location.
=> RES-1619 Can't load groups page where user and group location are the same.

app/Http/Controllers/PartyController.php, app/Http/Controllers/UserController.php, resources/lang/en/profile.php, routes/web.php, tests/Feature/Events/CreateEventTest.php, tests/Feature/Events/JoinEventTest.php, tests/Feature/Users/ProfileTest.php, tests/Feature/Users/UserAdminTest.php
Various:
- Fix Sentry errors in joining event by checking data more carefully.
- Remove some dead postEdit code (please check)
- Add some tests for coverage and internationalise a bit while we're in there.
=> RES-1622 sentry

app/Services/DiscourseService.php, tests/TestCase.php
=> RES-1618 Shouldn't sync deleted members to Discourse.

resources/js/app.js, resources/views/auth/login.blade.php
This prevents a double-click on the login button, which can result in a 419 page.
=> RES-1620- Possible fix for 419 login error.

app/Device.php, app/Helpers/LcaStats.php, app/Http/Controllers/DeviceController.php, app/Party.php, database/migrations/2022_02_04_140651_refactor_estimate_column.php
Refactors stats calculations to remove redundant type checking and coalescing.
Refactors edit methods in DeviceController to handle default estimate value.
Removes duplicate estimate assignment in DeviceController edit method.
=> Refactors devices.estimate column from varchar to decimal.

tools/deeplapi.php
=> Adds script for pulling translation strings from DeepL

app/Http/Controllers/GroupController.php
Use expandEvent method from PartyController.
=> RES-1660 Events not showing on single group pages

resources/js/components/EventPage.vue
Logic broken in a recent rework.
=> RES-1666 Allow devices to be added for events starting soon.

resources/js/app.js, resources/js/components/DashboardBanner.vue
Fix Sentry error caused by inviting an invalid email address.
Change banner for Big Give.
=> RES-1679 sentry

app/Helpers/Fixometer.php, app/Http/Controllers/GroupController.php, app/Http/Controllers/PartyController.php, app/User.php, tests/Feature/Events/AddRemoveVolunteerTest.php, tests/Feature/Groups/GroupHostTest.php
Add some extra tests and fix the logic for network coordinators removing from events/groups.
=> RES-1668 network coord remove

app/Http/Controllers/API/EventController.php, app/Http/Controllers/API/GroupController.php, app/Http/Resources/Group.php, app/Http/Resources/GroupSummary.php, app/Http/Resources/Party.php, app/Http/Resources/PartySummary.php, app/Http/Resources/PartySummaryCollection.php, routes/api.php, tests/Feature/Events/APIv2EventTest.php, tests/Feature/Groups/APIv2GroupTest.php
This adds a new /api/v2 group which we will use for gradually producing a better version of the API.
We use Eloquent resources and resource collections.  These allow us to:
- return the data easily
- only return the attributes we want to
- rename the attributes to have better names.
=> RES-1672 APIv2

app/Http/Controllers/GroupController.php, resources/views/group/create.blade.php, resources/views/group/edit.blade.php, tests/Feature/Groups/GroupCreateTest.php
- Add timezone as a parameter on group create.
- Ensure timezone shows on group edit.
- Tidy up the screen layout slightly to improve alignment.-
=> RES-1715 Allow hosts to set timezone on group create.

app/Notifications/AdminAbnormalDevices.php, app/Notifications/AdminModerationEvent.php, app/Notifications/AdminModerationEventPhotos.php, app/Notifications/AdminModerationGroup.php, app/Notifications/AdminNewUser.php, app/Notifications/AdminUserDeleted.php, app/Notifications/AdminWordPressCreateEventFailure.php, app/Notifications/AdminWordPressCreateGroupFailure.php, app/Notifications/AdminWordPressEditEventFailure.php, app/Notifications/AdminWordPressEditGroupFailure.php, app/Notifications/BaseNotification.php, app/Notifications/DeleteEventFromWordpressFailed.php, app/Notifications/EventConfirmed.php, app/Notifications/EventDevices.php, app/Notifications/EventRepairs.php, app/Notifications/GroupConfirmed.php, app/Notifications/JoinEvent.php, app/Notifications/JoinGroup.php, app/Notifications/NewDiscourseMember.php, app/Notifications/NewGroupMember.php, app/Notifications/NewGroupWithinRadius.php, app/Notifications/NotifyAdminNoDevices.php, app/Notifications/NotifyRestartersOfNewEvent.php, app/Notifications/RSVPEvent.php, app/Notifications/ResetPassword.php, tests/Feature/Events/CreateEventTest.php, tests/Feature/Events/InviteEventTest.php, tests/Feature/Notifications/BasicTest.php, tests/TestCase.php
1. Move some duplicate code into BaseNotification.
2. Make BaseNotification queue.
3. Fix up tests.
=> RES-1697 email queueing

database/migrations/2022_07_19_093250_add_brand_indexes.php
Adds migration to add indexes on brand columns to devices and brands tables
=> DAT-702 brand indexes

app/Notifications/AdminModerationEvent.php, resources/lang/en/profile.php, resources/lang/fr-BE/profile.php, resources/lang/fr/profile.php, resources/views/user/notifications.blade.php, resources/views/user/profile/profile.blade.php
Translated some things which weren't.
I've included a translation of the subject line of the new event notification, because we happen to already have it and it would make the web look more consistent.  But as discussed the body of the email isn't translated yet.
=> RES-1747 Missing translations.

resources/js/components/GroupActions.vue, resources/js/store/groups.js, tests/Integration/group.test.js, tests/Integration/utils.js
Failing because we didn't pass the API key.  Fixed and playwright test added.
=> RES-1746 Can't unfollow group

resources/wiki/css/_miscellaneous.scss, resources/wiki/css/components/_alerts.scss
Change our CSS a bit to allow the TOC to show if a specific class is used.
=> RES-1720 Allow showing of Wiki TOC

app/Group.php, app/Http/Controllers/API/EventController.php, app/Http/Controllers/API/GroupController.php, app/Http/Controllers/API/NetworkController.php, app/Http/Resources/GroupSummary.php, tests/Feature/Events/APIv2EventTest.php, tests/Feature/Events/DeleteEventTest.php, tests/Feature/Events/WordpressEventPushTest.php, tests/Feature/Groups/WordpressGroupPushTest.php, tests/Feature/Networks/APIv2NetworkTest.php, tests/Unit/GroupTest.php
Both pushing to WordPress and in the API.
=> RES-1757 don't publish approved events on unapproved groups

resources/js/components/EventDevice.vue
=> RES-1765 Fix header colour on add device

app/Console/Commands/ImportGroups.php, app/Console/Commands/ImportMRES.php, app/Group.php, app/Http/Controllers/GroupController.php, app/Http/Resources/Group.php, database/migrations/2022_09_19_135345_add_group_phone.php, phpunit.xml, resources/js/components/GroupDescription.vue, resources/lang/en/groups.php, resources/lang/fr-BE/groups.php, resources/lang/fr/groups.php, resources/views/group/create.blade.php, resources/views/group/edit.blade.php, tests/Unit/GroupTest.php
Add phone number to group.
Review comments from 1725.
=> RES-1756 Import MRES

app/Notifications/JoinEvent.php, resources/lang/en/groups.php, resources/lang/en/networks.php, resources/lang/en/notifications.php, resources/lang/fr-BE/groups.php, resources/lang/fr-BE/networks.php, resources/lang/fr-BE/notifications.php, resources/lang/fr/groups.php, resources/lang/fr/networks.php, resources/lang/fr/notifications.php, resources/views/networks/show.blade.php
Translate networks page, fix missing translations.
=> RES-1775 Translations

resources/wiki/css/_miscellaneous.scss
=> RES-1764 wiki issues

app/Helpers/FixometerFile.php
This code is quite confusing, what with the single vs multiple and test vs real variants.  I've done a conservative fix which makes that upload work.
=> RES-1772 Can't upload event image

app/Console/Commands/WordpressCreateEvent.php, app/Console/Commands/WordpressCreateGroup.php, app/Listeners/CreateWordpressPostForEvent.php, app/Listeners/CreateWordpressPostForGroup.php
Refactor code a little to allow artisan commands to push group/event to WordPress.
=> RES-1774 Wordpress groups

app/Http/Controllers/API/NetworkController.php
Similarly to `app\Http\Controllers\API\GroupController::getEventsForGroupv2`, allow filtering of network events by start and end date of event.
We already had filtering by updated date, but this is for the actual event date.
=> RES-1810: Allow client to pass start/end date filters for network's event list

app/Http/Controllers/DeviceController.php, tests/Feature/Devices/EditTest.php
=> RES-1818 Next steps of professional help & DIY are swapped in edit

app/Listeners/CreateWordpressPostForEvent.php, app/Listeners/CreateWordpressPostForGroup.php
Bug introduced by group approval changes.
=> RES-1851 Not creating group in Wordpress on group approval

app/Http/Controllers/PartyController.php, resources/views/events/view.blade.php
Group image expansion lost in earlier refactor.
=> RES-1838 Events don't show group logo

resources/js/components/EventDetails.vue, resources/js/components/GroupDescription.vue
Remove some styling which does precisely what we don't want.
=> RES-1838 Change line-height in descriptions

resources/global/css/components/_buttons.scss, resources/global/css/components/_card-talk.scss, resources/global/css/components/_custom-check-tick.scss, resources/global/css/components/_forms.scss, resources/global/css/components/_lists.scss, resources/global/css/components/_navigation-bar.scss, resources/global/css/components/_row-columns.scss, resources/global/css/components/_tables.scss, resources/global/css/components/_tabs.scss, resources/global/css/helpers/_hr.scss, resources/wiki/css/app.scss, resources/wiki/css/components/_edit-page-button.scss, resources/wiki/css/components/_row-arrows.scss
This was slightly broken by recent changes:
- Arrow bullets lost
- Header numbers and square lost
=> RES-1822 wiki front page styling

.circleci/config.yml, playwright.config.js, resources/js/components/DeviceAge.vue, resources/js/components/EventDeviceSummary.vue, tests/Integration/utils.js
On the summary, show a zero age as '-'.  When editing, show a zero age as blank.
Add a playwright test.
=> RES-1839 Record event age as 0 internally but show it as - or empty

resources/wiki/css/app.scss
=> RES-1850 H3 titles hidden when editing wiki

app/Http/Controllers/CalendarEventsController.php, routes/web.php, tests/Feature/Calendar/CalendarTest.php
=> RES-1868 Add calendar link for network

app/Helpers/Fixometer.php, tests/Feature/Devices/EditTest.php
Permissions code doesn't consider that case.
=> Network Coordinator can't edit device data

app/Console/Commands/SyncNetworkUsersToDiscourseGroup.php
The old script only sync'd users with `repair_network` set to the network, but that wouldn't work when a network was created after groups/users already existed.
This syncs any users who follow groups in the network.  But it doesn't reset the `repair_network` field - please consider.
=> RES-1855 Improve command to sync users for network to Discourse group

app/Helpers/Fixometer.php, tests/Feature/Events/CreateEventTest.php
More bad login in permissions code.
=> RES-1891 NetworkCoordinator sees create event option but can't actually create

app/Group.php, app/Http/Controllers/API/EventController.php, app/Party.php, tests/Feature/Events/APIv2EventTest.php, tests/Feature/Networks/NetworkTest.php
Over-zealous deletion of code.  Added tests.
=> RES-1890 update_at attribute is returning current time for all events

.circleci/config.yml, app/Console/Commands/DiscourseChangeSetting.php, app/Console/Commands/UserCreate.php, app/Group.php, app/Listeners/AddUserToDiscourseGroup.php, app/Listeners/CreateDiscourseThreadForEvent.php, app/Services/DiscourseService.php, tests/Feature/Events/InviteEventTest.php
I've done some work trying - but not succeeding - in getting Discourse testing to work better on Circle.
I think the changes in this PR are safe to release, so I'd like to get them in.
=> RES-1882 Sentry

app/Http/Controllers/ExportController.php, database/factories/CategoryFactory.php, tests/Feature/Events/ExportTest.php, tests/Feature/Groups/GroupViewTest.php
Add a powered/unpowered flag to the export, and remove the obsolete code which exports different fields based on the domain.
=> RES-1918 Add powered/unpowered column to exports

resources/js/components/DeviceCategorySelect.vue, resources/js/components/GroupAddEdit.vue
The misc category is now added at the bottom, with a different name.  It shouldn't also appear in the middle of the list.
=> RES-1939 Misc category shouldn't appear in list

resources/js/components/DeviceType.vue, tests/Integration/utils.js
We have to do this slightly hackily, but it works.
=> RES-1952 Autofocus on type input when adding data

resources/js/store/events.js
=> RES-1952 Broke event store for old code.

tests/Feature/Events/APIv2EventTest.php, tests/Feature/Groups/APIv2GroupTest.php
Add a specific test for both v1 and v2 APIs, and also fix an unreliability in an event test.
=> RES-1965 Test that updating group network data updates the updated_at timestamp

app/Console/Commands/DiscourseCreateThread.php, app/Listeners/CreateDiscourseThreadForEvent.php
The Discourse API changed.
We will follow up separately for how we should detect this.
=> RES-1970 Discourse private message creation is broken

app/Console/Commands/WordpressCreateEventMissing.php
For running in failure situations.
=> RES-1975 Artisan command to create missing events

app/Http/Controllers/API/EventController.php, app/Http/Controllers/DashboardController.php, app/Network.php, resources/js/components/DashboardPage.vue, resources/js/components/DashboardYourGroups.vue, tests/Feature/Events/APIv2EventTest.php, tests/Unit/NetworkTest.php, tests/Unit/NetworkTests.php
=> RES-1960 Include past events in the list of events to moderate

lang/en/groups.php, lang/fr-BE/groups.php, lang/fr/groups.php, resources/js/components/GroupPage.vue, resources/js/components/GroupVolunteer.vue, resources/js/components/GroupVolunteers.vue, resources/js/mixins/group.js, resources/js/store/volunteers.js, resources/views/group/view.blade.php, tests/Feature/Groups/GroupHostTest.php
Adds this option to the volunteer management dropdown.
=> RES-1987 Allow network coordinators to remove host role on a group

resources/js/components/GroupVolunteer.vue
Fix them so that they now work.
=> RES-1993 Volunteer links broken in recent merge

resources/js/components/EventAddVolunteerModal.vue
This was broken by recent API work.
=> RES-1994 Can't add volunteer to past event

app/Group.php, app/Services/DiscourseService.php, tests/Feature/Commands/DiscourseTest.php
Releasing to production for testing purposes.
=> RES-2013 Rename Discourse group when the Restarters group is renamed

app/Http/Controllers/ExportController.php
Ignore iconv errors during export, as per https://stackoverflow.com/questions/8727735/iconv-detected-an-illegal-character-in-input-string
=> RES-2022 emoji export error

app/Http/Controllers/GroupController.php, lang/en/groups.php, lang/fr-BE/groups.php, lang/fr/groups.php, resources/js/components/GroupActions.vue, routes/web.php, tests/Feature/Groups/InviteGroupTest.php
This function was deleted, but the menu option and some other code still existed.
=> Remove some lingering code to invite nearby volunteers
